FROM arm64v8/python:3.7-slim-buster

COPY qemu-aarch64-static /usr/bin/qemu-aarch64-static
RUN cd /usr/bin && chmod a+rwx qemu-aarch64-static

RUN mkdir /frame_volume && chmod -R 777 /frame_volume
RUN mkdir /annotated_frame_volume && chmod -R 777 /annotated_frame_volume
RUN mkdir /retrain_frame_volume && chmod -R 777 /retrain_frame_volume

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]