# start with standard public influx image
FROM arm64v8/influxdb:1.8.10
EXPOSE 8088
COPY qemu-aarch64-static /usr/bin/qemu-aarch64-static
RUN cd /usr/bin && chmod a+rwx qemu-aarch64-static

# copy in our database initialization script
# creates telemetry database and sets retention policy
COPY initdb.iql /docker-entrypoint-initdb.d/init.iql

# copy in our config
COPY influxdb.conf /etc/influxdb/influxdb.conf

# launch influx daemon
CMD ["influxd"]